services:
  app:
    build:
      context: .
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 8000:8000
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_SIZE=small
