services:
  app:
    build:
      context: .
    command: "poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    # command: "tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 8001:8001
    volumes:
      - .:/asr_service:cached
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_SIZE=small
